### ISSUE TITLE
Pendot Designer traceback

### ISSUE THREAD

**Issue by n7s** [simoncozens/Dotter#16]
In Glyphs 3.3 (3307) using Python 3.11.9 (Glyphs), and the latest Dotter (d3c2445) I get the following traceback in the Macro Panel output: (No Pendot Designer dialog box shows) 

```
Dot Size 15
Dot Spacing 15
Prevent Overlaps True
Split Paths False
Contour Source <Default>
Stroker Width 50
Stroker Height 50
Stroker Angle 0
Start Cap round
End Cap round
Join Type round
Remove External False
Remove Internal False
Segment Wise False
Dot Size 30
Traceback (most recent call last):
  File "Pendot Designer.py", line 599
    setattr(GSApplication, "_pendotdesigner", PendotDesigner())
                                              ^^^^^^^^^^^^^^^^
  File "Pendot Designer.py", line 346, in __init__
    self.on_layer_change()
  File "Pendot Designer.py", line 516, in on_layer_change
    self.reload_values()
  File "Pendot Designer.py", line 528, in reload_values
    self.reload_guidelines()
  File "Pendot Designer.py", line 473, in reload_guidelines
    [
TypeError: 'NoneType' object is not iterable
```

**Comment by simoncozens** [comment]
oops, this was fixed locally but I didn't commit it.

**Comment by jvgaultney** [comment]
If I open a New Font, with nothing in it, I get:

Traceback (most recent call last):
  File "Pendot Designer.py", line 600
    setattr(GSApplication, "_pendotdesigner", PendotDesigner())
                                              ^^^^^^^^^^^^^^^^
  File "Pendot Designer.py", line 275, in __init__
    instance = self.selectedInstance or Glyphs.font.instances[0]
                                        ~~~~~~~~~~~~~~~~~~~~~^^^
  File "GlyphsApp/GlyphsApp/__init__.py", line 2087, in __getitem__
  File "GlyphsApp/GlyphsApp/__init__.py", line 567, in _validate_idx
IndexError: list index 0 out of range 0
